version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: budget_survey_db_dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-dev_root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-survey_dev}
      MYSQL_USER: ${MYSQL_USER:-survey_dev}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dev_password}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - db_data_dev:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - budget_survey_network_dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s
    restart: unless-stopped

  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: budget_survey_app_dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE:-survey_dev}
      - MYSQL_USER=${MYSQL_USER:-survey_dev}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-dev_password}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-dev-secret-key}
      - SURVEY_BASE_URL=http://localhost:5000
    ports:
      - "${DEV_APP_PORT:-5000}:5001"
    volumes:
      # Mount source code for live reloading
      - .:/app
      - /app/venv  # Exclude venv from mounting
      - /app/__pycache__  # Exclude cache from mounting
      - app_logs_dev:/app/logs
      - app_data_dev:/app/data
    networks:
      - budget_survey_network_dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    # Enable debugging
    stdin_open: true
    tty: true

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: budget_survey_phpmyadmin_dev
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER:-survey_dev}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-dev_password}
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    networks:
      - budget_survey_network_dev
    restart: unless-stopped

  # Optional: Mailhog for email testing
  mailhog:
    image: mailhog/mailhog
    container_name: budget_survey_mailhog_dev
    ports:
      - "${MAILHOG_SMTP_PORT:-1025}:1025"
      - "${MAILHOG_WEB_PORT:-8025}:8025"
    networks:
      - budget_survey_network_dev
    restart: unless-stopped

networks:
  budget_survey_network_dev:
    driver: bridge

volumes:
  db_data_dev:
    driver: local
  app_logs_dev:
    driver: local
  app_data_dev:
    driver: local 