[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'

[tool.ruff]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Also enable isort (`I`) for import sorting.
lint.select = ["E", "F", "I"]

# Ignore `E501` (line length violations).
lint.ignore = ["E501"]

# Same as Black.
line-length = 88
indent-width = 4

# Target Python 3.12
target-version = "py312"

# Allow fixes for all enabled rules (when `--fix`) is provided.
lint.fixable = ["ALL"]

# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Use double quotes for strings.
quote-style = "double"

# Use spaces for indentation.
indent-style = "space"

# Respect magic trailing commas.
skip-magic-trailing-comma = false

# Automatically detect the appropriate line ending.
line-ending = "auto"

[tool.pytest.ini_options]
# Test file patterns
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*", "*Test"]
python_functions = ["test_*"]

# Test paths to search
testpaths = ["tests"]

# Logging setup
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

# Warning filters
filterwarnings = [
    "ignore::RuntimeWarning",
    "ignore::UserWarning",
    "ignore::DeprecationWarning"
]

# Markers
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks integration tests",
    "unit: marks unit tests"
]

# Default timeout for tests (in seconds)
timeout = 300

# Show extra test summary info
addopts = """
    --verbose
    --showlocals
    --tb=short
    --strict-markers
    -ra
"""